#pragma once

// This file is included from assembly.
// Use only preprocessor definitions here.

// GS segment (= AssemblyCpuData) offsets.
#define THOR_GS_SELF 0x0
#define THOR_GS_EXECUTOR 0x8
#define THOR_GS_SYSCALL_STACK 0x10
#define THOR_GS_ISEQ_PTR 0x18
#define THOR_GS_SECURITY_TRANSITION_COUNTERS 0x20
#define THOR_GS_SECURITY_RAW_USER_ENTRY_COUNT 0x20
#define THOR_GS_SECURITY_TRUSTED_ENTRY_STATE_COUNT 0x28
#define THOR_GS_SECURITY_USER_RETURN_PREPARATION_COUNT 0x30
#define THOR_GS_SECURITY_FINAL_USER_RETURN_COUNT 0x38
#define THOR_GS_SECURITY_CONTEXT_CHANGE_COUNT 0x40
#define THOR_GS_SECURITY_PRE_VM_ENTRY_COUNT 0x48
#define THOR_GS_SECURITY_POST_VM_EXIT_COUNT 0x50
#define THOR_GS_SECURITY_PRE_IDLE_COUNT 0x58
#define THOR_GS_SECURITY_POST_IDLE_COUNT 0x60
#define THOR_GS_SECURITY_NMI_ENTRY_COUNT 0x68
#define THOR_GS_SECURITY_NMI_RETURN_COUNT 0x70

#define THOR_EXECUTOR_UAR 0x18
